collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6114739
  brandStrength: 0
  rhythmicContrast: 0.2127302
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.665112
typography_spectrum: 0.556903
layout_spectrum: 0.7789179
name: The New Austinians
