layout_spectrum: 0.7691231
typography_spectrum: 0.556903
color:
  saturation: 0.6114739
  lightness: 0.665112
  brandStrength: 0
  rhythmicContrast: 0.2127302
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: The New Austinians
